apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-pipeline-specref-1
spec:
  pipelineSpec:
    tasks:
      - name: hello
        taskRef:
          name: hello
      - name: goodbye
        taskRef:
          name: goodbye
