apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipelinerun-volume-2
spec:
  pipelineRef:
    name: pipeline-volume
  params:
    - name: giturl
      value: 10.0.7.30/node/vue.git
    - name: branch
      value: main
  workspaces:
    - name: code
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 12M
    - name: aliyun-image-registry-secert
      secret:
        secretName: aliyun-image-registry-secert
