apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
   name: canary-demo
   namespace: test-app
   annotations:
      app.oam.dev/publishVersion: v1
spec:
   components:
      - name: canary-demo
        type: webservice
        properties:
           image: wangyikewyk/canarydemo:v1
           ports:
              - port: 8090
        traits:
           - type: scaler
             properties:
                replicas: 3
           - type: gateway
             properties:
                domain: canary-deploy.1853whitleyave.com
                http:
                   "/version": 8090
