apiVersion: core.oam.dev/v1beta1  
kind: Application  
metadata:  
  name: my-app  
spec:  
  components:  
    - name: my-raw-deployment  
      type: raw  
      properties:  
        apiVersion: apps/v1  
        kind: Deployment  
        spec:  
          replicas: 3  
          selector:  
            matchLabels:  
              app: my-app  
          template:  
            metadata:  
              labels:  
                app: my-app  
            spec:  
              containers:  
                - name: my-app  
                  image: nginx:1.19.1  
                  ports:  
                    - containerPort: 80
