apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: goodbye
      image: ubuntu
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/bash
        echo "Goodbye goodby"   
