apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: node-tekton.1853whitleyave.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: el-event-listener
            port:
             number: 8080
