apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-tt
spec:
  params:
    - name: giturl
      type: string
    - name: branch
      type: string
  tasks:
    - name: clone
      taskRef:
        name: test-trigger
      params:
        - name: giturl
          value: "$(params.giturl)"
        - name: branch
          value: "$(params.branch)"
