apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-npm-cache-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs/npm-cache
    server: 10.0.7.11
