apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-blue-green
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook-blue-green
    repoURL: http://10.0.7.63/argocd/appconfig.git
    targetRevision: HEAD
    
    
